language: c
dist: trusty

compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=1.3.0
  - MRUBY_VERSION=master
branches:
  only:
    - master

addons:
  apt:
    packages:
      - rake
      - bison
      - git
      - gperf
script:
  - rake test
